#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/5/13 10:57
# @Author  : jiakang
# @File    : sman
# @Software: IntelliJ IDEA

import os, sys

sman_path = '/Users/jiakang/sman/sman'
command = 'python %s %s' % (sman_path, str.join(' ', sys.argv[1:]))
# print(command)
os.system(command)
