#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/5/13 12:15
# @Author  : jiakang
# @File    : test
# @Software: IntelliJ IDEA
# sman_notes: script to test whether sman works well.

import sys


def do_test():
    args = sys.argv
    print('This is test script, you input: %s' % args)


if __name__ == '__main__':
    do_test()
